### ISSUE TITLE
`runJavaScript` to `core-kit`?

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#273] opened 2023-12-22 22:19 UTC
When using the new syntax `code()` and `recipe`, it requires `runJavaScript` and `invoke`, both of which are in different kits.

Should they be in the same kit? 

We don't notice it in things like `breadboard-ui` because we always include them, however on the CLI and any apps I build I now have to make sure I always include them.

**Comment by dglazkov** [comment] 2024-01-21 19:18
Dupe of #177

**Closed by dglazkov** 2024-01-21 19:18 UTC
